### ISSUE TITLE
Package conflicts detection in large compound projects

### ISSUE THREAD

**Issue by Nirvanchik** [pradyunsg/zazo#13]
In our project we install dependencies from 2 large subprojects. Installation command looks like:

```
pip install -r requirements.txt
pip install -r subproject/requirements.txt
```
or in CI builds it looks like:
```
pip install -r requirements.txt subproject/requirements.txt
```

Will this new package resolver be able to handle conflicts in such conditions (when it installs them from multiple requirements) ?

Currently, we have made our own checker (run with py.test) which manually reads `requirements.txt` and `subproject/requirements.txt` using `pip.req.parse_requirements()` and compares them.
And all our deps with transitive deps are freezed (using "==").
Also, we have freezed deps in many our internal pip packages. But eventually this makes upgrading one small dependency to hell. So we don't like our solution and treat it rather as a workaround.

Recently pip (in version 10+) made `req` an internal package. So it's kind of hiding this hole from us :-(

**Comment by pradyunsg** [comment]
Hey!

I'm not sure I understand what you are asking here... Are you asking if it would be able to "merge" multiple requirements like "A>1.0 + A<3.0" to "A>1.0,<3.0"? Yes, it should be able to do this.

FWIW, distlib has a helper to parse requirement files so, you might be able to use that.

**Comment by pradyunsg** [comment]
Hey @Nirvanchik!

I think I've answered your question here so I'm going to go ahead and close this, since there's nothing directly actionable here.

**Comment by merwok** [comment]
Another way is to prevent conflict at the freeze step: instead of having two independent files, or including one file from the other with `-r`, you can add a line `-c path/to/other/frozen/reqs` which means «use requirements in that other file as constraints for version resolution»
