### ISSUE TITLE
Do not overwrite files from already-installed packages

### ISSUE THREAD

**Issue by davidedelvento** [pradyunsg/zazo#18]
Following the suggestion in https://github.com/pypa/pip/issues/988#issuecomment-608040274 I am submitting this test case here.

Instead of just repeating myself, the issue is https://github.com/pypa/pip/issues/4625

Not sure if that is in scope with the new dependency resolver, but mentioning it and let you think about it for a moment can't hurt.

**Comment by davidedelvento** [comment]
This and #17 are two different things. This one is the most serious and is about pip silently overwriting files from previous packages it installed. In brief, if two unrelated packages `a` and `b` both have a `foo.py` file, in some circumstances (see https://github.com/pypa/pip/issues/4625 for details) the second that gets installed overwrites the first, and pip does not notice.

Again, I am not sure if solving the issue is in the scope of what you are working on at the moment, but...

**Comment by pradyunsg** [comment]
Okay, I closed this for the wrong reasons earlier. However, this is not in scope for this project and is the same request as https://github.com/pypa/pip/issues/4625.

I'm going to go ahead and close this in favor of that issue.
